### ISSUE TITLE
search not working on https://software.manjaro.org

### ISSUE THREAD

**Issue by andy5995** [Manjaro-WebDad/manjaro-applications-discovery#2]
I got here via the link on the main menu at https://software.manjaro.org/

I'm not sure how related this project is to the website, but the search isn't working. In the search field, when I type in "gcc" or "timeshift", the page only reloads.

I'm using Firefox 100.0 (64-bit) on Manjaro 21.2.6

**Comment by codesardine** [comment]
There is an issue with the search that needs to be fixed as it does not show packages without appstream data, but I am not experiencing any page reloads on my end.

**Comment by codesardine** [comment]
This should now be fixed.
