### ISSUE TITLE
Doesn't work with flatpaks

### ISSUE THREAD

**Issue by tio-trom** [Manjaro-WebDad/manjaro-applications-discovery#3]
Works ok with the rest but not flatpaks. Clicking to install nothing happens - like an example https://software.manjaro.org/flatpak/com.sweetscape.ZeroOneZeroEditor#!

`web-pamac://flatpak=com.sweetscape.ZeroOneZeroEditor` should normally work but it does not. It used to work. Anything changed in regards to the flatpaks?

**Comment by codesardine** [comment]
Seems to work on my end
